# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 34) do

  create_table "carddetails", :force => true do |t|
    t.column "bin",        :string
    t.column "product",    :string
    t.column "expiredate", :datetime
    t.column "priority",   :integer
  end

  create_table "cities", :force => true do |t|
    t.column "cityname", :string, :default => "NULL"
  end

  create_table "clusters", :force => true do |t|
    t.column "CLST_ClusterID",      :integer
    t.column "CLST_ClusterName",    :string
    t.column "CLST_RegionID",       :integer
    t.column "created_at",          :datetime
    t.column "CLST_CreatedBy",      :integer
    t.column "updated_at",          :datetime
    t.column "CLST_LastModifiedBy", :integer
  end

  create_table "data_export_statuses", :force => true do |t|
    t.column "EXP_LocationID",           :string
    t.column "EXP_RegionID",             :integer
    t.column "EXP_Date",                 :datetime
    t.column "EXP_MasterName",           :string
    t.column "EXP_FullExport",           :string
    t.column "EXP_ExportCompleted",      :string,   :limit => 1
    t.column "EXP_ErrorDescription",     :string
    t.column "EXP_MachineStatus",        :string
    t.column "EXP_NoOfRecordsSent",      :integer
    t.column "EXP_NoOfRecordsConfirmed", :integer
    t.column "created_at",               :datetime
    t.column "EXP_CreatedBy",            :integer
    t.column "updated_at",               :datetime
    t.column "EXP_LastModifiedBy",       :integer
  end

  create_table "data_import_statuses", :force => true do |t|
    t.column "IMP_LocationID",       :string
    t.column "IMP_RegionID",         :integer
    t.column "IMP_Date",             :datetime
    t.column "IMP_ImportCompleted",  :string,   :limit => 1
    t.column "IMP_ErrorDescription", :string
    t.column "IMP_MachineStatus",    :string
    t.column "created_at",           :datetime
    t.column "IMP_CreatedBy",        :integer
    t.column "updated_at",           :datetime
    t.column "IMP_LastModifiedBy",   :integer
    t.column "IMP_TDate",            :datetime
  end

  create_table "display_scroll_messages", :force => true do |t|
    t.column "SCRL_DisplayScrollMessageID", :integer
    t.column "SCRL_DisplayScrollMessage",   :string
    t.column "created_at",                  :datetime
    t.column "SCRL_CreatedBy",              :integer
    t.column "updated_at",                  :datetime
    t.column "SCRL_LastModifiedBy",         :integer
  end

  create_table "dqmvendors", :force => true do |t|
    t.column "VND_VendorID",          :integer
    t.column "VND_VendorName",        :string
    t.column "VND_Address",           :string
    t.column "VND_ContactPersonName", :string
    t.column "VND_ContactEmailID",    :string
    t.column "VND_Telephone",         :string
    t.column "VND_Fax",               :string
    t.column "created_at",            :datetime
    t.column "VND_CreatedBy",         :integer
    t.column "updated_at",            :datetime
    t.column "VND_LastModifiedBy",    :integer
  end

  create_table "groups", :force => true do |t|
    t.column "GRP_GroupID",          :integer
    t.column "GRP_GroupName",        :string
    t.column "GRP_GroupDescription", :string
    t.column "created_at",           :datetime
    t.column "GRP_CreatedBy",        :integer
    t.column "updated_at",           :datetime
    t.column "GRP_LastModifiedBy",   :integer
  end

  create_table "locations", :force => true do |t|
    t.column "LOC_LocationID",        :integer
    t.column "LOC_SoleID",            :string
    t.column "LOC_BranchName",        :string
    t.column "LOC_ClusterID",         :integer
    t.column "LOC_GroupID",           :integer
    t.column "LOC_NoOfEmployees",     :integer
    t.column "LOC_DQM_IPAddress",     :string
    t.column "LOC_IsActive",          :string,   :limit => 1
    t.column "LOC_ReasonForInactive", :string
    t.column "LOC_DQMVendorID",       :integer
    t.column "created_at",            :datetime
    t.column "LOC_CreatedBy",         :integer
    t.column "updated_at",            :datetime
    t.column "LOC_LastModifiedBy",    :integer
  end

  create_table "non_stp_reasons", :force => true do |t|
    t.column "NSTP_NonSTPID",       :integer
    t.column "NSTP_NonSTPReason",   :string
    t.column "NSTP_GroupID",        :integer
    t.column "created_at",          :datetime
    t.column "NSTP_CreatedBy",      :integer
    t.column "updated_at",          :datetime
    t.column "NSTP_LastModifiedBy", :integer
  end

  create_table "old_pause_dets", :force => true do |t|
    t.column "CNTNo",      :integer
    t.column "UserID",     :string
    t.column "PDate",      :datetime
    t.column "STime",      :datetime
    t.column "ETime",      :datetime
    t.column "Reason",     :string,   :limit => 1
    t.column "PS",         :string,   :limit => 1
    t.column "LocationId", :integer
  end

  create_table "old_token_masters", :force => true do |t|
    t.column "sno",         :integer
    t.column "tokenno",     :integer
    t.column "token",       :string,   :limit => 1
    t.column "ctypeid",     :string,   :limit => 1
    t.column "serviceid",   :string,   :limit => 1
    t.column "tokendate",   :datetime
    t.column "tokentime",   :datetime
    t.column "counterno",   :integer
    t.column "Accno",       :integer
    t.column "call",        :string,   :limit => 1
    t.column "focus",       :string,   :limit => 1
    t.column "calltime",    :datetime
    t.column "calltime2",   :datetime
    t.column "visible",     :string,   :limit => 1
    t.column "servicetime", :datetime
    t.column "running",     :string,   :limit => 1
    t.column "skip",        :string,   :limit => 1
    t.column "noofskips",   :integer
    t.column "completed",   :string,   :limit => 1
    t.column "NonSTPName",  :string
    t.column "STPName",     :string
    t.column "PauseFlag",   :integer
    t.column "Pausetime",   :datetime
    t.column "Releasetime", :datetime
    t.column "locationid",  :integer
    t.column "exported",    :string,   :limit => 1
    t.column "exportedON",  :datetime
    t.column "userid",      :string,   :limit => 1
    t.column "LSERVER",     :string,   :limit => 1
    t.column "DQMIP",       :string
    t.column "DISPLAYVER",  :integer
    t.column "CSOIP",       :string
    t.column "CASHIERVER",  :integer
    t.column "NoOfCheques", :integer
  end

  create_table "pause_details", :force => true do |t|
    t.column "PD_PauseDetailID",  :integer
    t.column "PD_LocationID",     :integer
    t.column "PD_CounterNo",      :integer
    t.column "PD_BranchUser",     :string,   :limit => 1
    t.column "PD_PauseTime",      :datetime
    t.column "PD_ReleaseTime",    :datetime
    t.column "PD_PauseReasonID",  :integer
    t.column "PD_PauseDate",      :datetime
    t.column "created_at",        :datetime
    t.column "PD_CreatedBy",      :integer
    t.column "updated_at",        :datetime
    t.column "PD_LastModifiedBy", :integer
  end

  create_table "pause_reasons", :force => true do |t|
    t.column "PR_PauseReasonID",   :integer
    t.column "PR_PauseReasonDesc", :string
    t.column "created_at",         :datetime
    t.column "PR_CreatedBy",       :integer
    t.column "updated_at",         :datetime
    t.column "PR_LastModifiedBy",  :integer
  end

  create_table "regions", :force => true do |t|
    t.column "REG_RegionID",       :integer
    t.column "REG_RegionName",     :string
    t.column "REG_ZoneID",         :integer
    t.column "created_at",         :datetime
    t.column "REG_CreatedBy",      :integer
    t.column "updated_at",         :datetime
    t.column "REG_LastModifiedBy", :integer
    t.column "emp_no",             :string,   :limit => 50
    t.column "emp_name",           :string,   :limit => 50
  end

  create_table "service_types", :force => true do |t|
    t.column "STYP_ServiceTypeID",   :string,   :limit => 1
    t.column "STYP_ServiceTypeName", :string
    t.column "created_at",           :datetime
    t.column "STYP_CreatedBy",       :integer
    t.column "updated_at",           :datetime
    t.column "STYP_LastModifiedBy",  :integer
  end

  create_table "services", :force => true do |t|
    t.column "SVC_ServiceID",         :string,   :limit => 50, :default => "NULL"
    t.column "SVC_ServiceName",       :string,                 :default => "NULL"
    t.column "SVC_ServiceAcronym",    :string,   :limit => 1,  :default => "NULL"
    t.column "SVC_GroupID",           :integer,                :default => 0
    t.column "SVC_ThresholdTimeMins", :datetime
    t.column "SVC_ButtonNo",          :integer,                :default => 0
    t.column "SVC_Priority",          :integer,                :default => 0
    t.column "SVC_ServiceTypeID",     :integer,                :default => 0
    t.column "SVC_FromHour",          :string,                 :default => "NULL"
    t.column "SVC_FromMinute",        :string,                 :default => "NULL"
    t.column "SVC_ToHour",            :string,                 :default => "NULL"
    t.column "SVC_ToMinute",          :string,                 :default => "NULL"
    t.column "SVC_IsActive",          :string,   :limit => 1,  :default => "NULL"
    t.column "created_at",            :datetime
    t.column "SVC_CreatedBy",         :integer,                :default => 0
    t.column "updated_at",            :datetime
    t.column "SVC_LastModifiedBy",    :integer,                :default => 0
    t.column "waitingforapproval",    :string
  end

  create_table "settings", :force => true do |t|
    t.column "purgingperiod", :integer
  end

  create_table "stp_reasons", :force => true do |t|
    t.column "STP_STPID",          :integer
    t.column "STP_STPReason",      :string
    t.column "STP_ServiceID",      :string,   :limit => 50
    t.column "created_at",         :datetime
    t.column "STP_CreatedBy",      :integer
    t.column "updated_at",         :datetime
    t.column "STP_LastModifiedBy", :integer
  end

  create_table "thresholdtimes", :force => true do |t|
    t.column "ctypeid",       :string
    t.column "ctypedesc",     :string
    t.column "priority",      :integer
    t.column "thresholdtime", :datetime
  end

  create_table "token_bottom_ads", :force => true do |t|
    t.column "BOT_TokenBottomAdID", :integer
    t.column "BOT_AdMessage",       :string
    t.column "created_at",          :datetime
    t.column "BOT_CreatedBy",       :integer
    t.column "updated_at",          :datetime
    t.column "BOT_LastModifiedBy",  :integer
    t.column "branchname",          :string,   :limit => 50
    t.column "author",              :string,   :limit => 50
  end

  create_table "token_numbers", :force => true do |t|
    t.column "Expr1000",           :integer
    t.column "lastserved",         :integer
    t.column "DrivePercent",       :integer
    t.column "SystemAvailability", :string
    t.column "ActiveUserCount",    :integer
    t.column "LocationID",         :integer
    t.column "ExportedFlag",       :string
    t.column "VarTimeStamp",       :datetime
    t.column "PrinterPaperStatus", :string
    t.column "Gold",               :integer
    t.column "Customer",           :integer
    t.column "NonCustomer",        :integer
    t.column "EmployeeNo",         :integer
    t.column "Ratio",              :integer
    t.column "SoleID",             :string
    t.column "PendingRatio",       :integer
  end

  create_table "tokens", :force => true do |t|
    t.column "LocationID",    :string
    t.column "DQM_IPAddress", :string
    t.column "SerialNo",      :integer
    t.column "tokenno",       :string
    t.column "tokenid",       :integer
    t.column "ctypeid",       :string
    t.column "transdate",     :datetime
    t.column "generatedtime", :string
    t.column "serviceid",     :string
    t.column "counterno",     :integer
    t.column "accountno",     :string
    t.column "login",         :string
    t.column "calledtime",    :string
    t.column "servicedtime",  :string
    t.column "timetaken",     :string
    t.column "waittime",      :string
    t.column "stpname",       :string
    t.column "nonstpname",    :string
    t.column "tokenstatus",   :integer
    t.column "pauseflag",     :integer
    t.column "pausetime",     :string
    t.column "releasetime",   :string
    t.column "bulkcount",     :integer
    t.column "reasons",       :string
    t.column "call1",         :string
    t.column "missingflag",   :integer
    t.column "pullcounter",   :integer
    t.column "redirecttime",  :string
    t.column "emp_no",        :string
    t.column "emp_name",      :string
  end

  add_index "tokens", ["LocationID", "DQM_IPAddress", "tokenno", "tokenid", "transdate", "serviceid"], :name => "Location"

# Could not dump table "transacts" because of following StandardError
#   Unknown type 'real(4)' for column 'score'

  create_table "tyche_new_dqm_branches", :force => true do |t|
    t.column "TYC_LocationID",     :integer
    t.column "created_at",         :datetime
    t.column "TYC_CreatedBy",      :integer
    t.column "updated_at",         :datetime
    t.column "TYC_LastModifiedBy", :integer
  end

  create_table "users", :force => true do |t|
    t.column "USR_UserName",   :string,                 :default => "NULL"
    t.column "login",          :string,                 :default => "NULL"
    t.column "password",       :string,                 :default => "NULL"
    t.column "USR_IsActive",   :integer,                :default => 0
    t.column "USR_Role",       :string,                 :default => "NULL"
    t.column "USR_GroupID",    :integer,                :default => 0
    t.column "USR_IsLogin",    :string,                 :default => "N"
    t.column "user_count",     :integer
    t.column "branch",         :string
    t.column "created_at",     :datetime
    t.column "updated_at",     :datetime
    t.column "ByWhom",         :string,   :limit => 50
    t.column "Activity",       :string,   :limit => 50
    t.column "lamid",          :string,   :limit => -1
    t.column "arid",           :integer
    t.column "userid",         :integer
    t.column "username",       :string,   :limit => 50
    t.column "solid",          :integer
    t.column "flag",           :string,   :limit => 50
    t.column "emailid",        :string,   :limit => 50
    t.column "rolecount",      :integer
    t.column "rolename1",      :string,   :limit => 50
    t.column "rolename2",      :string,   :limit => 50
    t.column "additional",     :string,   :limit => 50
    t.column "count",          :integer
    t.column "fieldid1",       :string,   :limit => 50
    t.column "fieldval1",      :string,   :limit => 50
    t.column "Output_Code",    :string,   :limit => 50
    t.column "Output_message", :string,   :limit => 50
  end

  create_table "zones", :force => true do |t|
    t.column "ZONE_ZoneID",         :integer
    t.column "ZONE_ZoneName",       :string
    t.column "ZONE_CreatedDate",    :datetime
    t.column "ZONE_CreatedBy",      :string
    t.column "updated_at",          :datetime
    t.column "ZONE_LastModifiedBy", :string
  end

end
